### ISSUE TITLE
Outline deployment question

### ISSUE THREAD

**Issue by enmanuelmoreira** [haraldkoch/kochhaus-home#3710]
Hi @haraldkoch. 

I tried to configure the deployment of outline, and I am getting some errors when I upload the user profile picture (Upload failed) I suspect that I have a misconfiguration of my minio deployment. Still following the docs that you wrote, I can't achieve this configuration.

```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:8080 / https://notes.domain.com"}
{"attempt":0,"event":{"actorId":"4d690ec7-4889-441e-9132-8324063a90d3","collectionId":null,"createdAt":"2023-12-30T15:20:57.488Z","data":{"name":"avatar.jpg"},"documentId":null,"id":"f1937b1b-0b5b-47f4-8365-191672a9e29a","ip":"192.168.x.x","modelId":"c5d867a7-dd76-4043-87ad-aba086844f9f","name":"attachments.create","teamId":"719e2d5e-9ba5-4467-8d25-1e5f25014c79","userId":null},"label":"worker","level":"info","message":"Processing attachments.create"}
{"event":{"actorId":"4d690ec7-4889-441e-9132-8324063a90d3","collectionId":null,"createdAt":"2023-12-30T15:20:57.488Z","data":{"name":"avatar.jpg"},"documentId":null,"id":"f1937b1b-0b5b-47f4-8365-191672a9e29a","ip":"192.168.x.x","modelId":"c5d867a7-dd76-4043-87ad-aba086844f9f","name":"attachments.create","teamId":"719e2d5e-9ba5-4467-8d25-1e5f25014c79","userId":null},"label":"worker","level":"info","message":"WebhookProcessor running attachments.create"}
```

When you configure outline with minio, you configure the aws_keys with the service account for the user `outline` or with the aws global keys?

Regards.

**Comment by haraldkoch** [comment]
I configure the AWS keys with the service account name (outline) and secret key; that's why the policy objects to grant access to (only) the outline bucket.

This configuration still works for me. The docs in my repository came from @onedr0p many moons ago; I recommend coming to the [Home Operations discord](https://discord.gg/home-operations) and opening a new thread in the Support channel, where several of us will be able to help you debug.

**Comment by enmanuelmoreira** [comment]
Thank you!
